# Generated by Django 6.0.1 on 2026-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
